#!/usr/bin/env python3
"""Build a single rule-to-evidence index for organizer/Jury review.

The matrix is deliberately conservative: an artifact can support a property
of the selected trace without proving that the extracted account's official
final result came from that trace.  Those scopes are kept in every row.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]

COMMON = {
    "one_account_no_teams": {
        "requirement": "Compete individually, use one Kaggle account, and do not share private competition material.",
        "official_source": "official rules page (individual participation)",
        "status": "evidence_partially_available",
        "scope": "all captured repository and Kaggle-account records",
        "evidence": ["task1/SUMMARY.json", "task2/SUMMARY.json", "task3/SUMMARY.json", "task4/SUMMARY.json", "task5/SUMMARY.json", "task6/SUMMARY.json", "KAGGLE_EXTRACTION_SUMMARY.json"],
        "note": "All captured competition actions identify account researai. Local records cannot independently prove that no other account, team relationship, or off-trace private sharing existed; the organizer decides whether the account history is sufficient.",
    },
}


def row(requirement: str, official_source: str, status: str, scope: str,
        evidence: list[str], note: str) -> dict[str, Any]:
    return {
        "requirement": requirement,
        "official_source": official_source,
        "status": status,
        "scope": scope,
        "evidence": evidence,
        "note": note,
    }


TASKS: dict[str, dict[str, Any]] = {
    "task1": {
        "competition": "ioai-2026-task-1-westlake-nlp-24",
        "official_final": "55267333 / 55267368 (Public 0.77751, Private 0.80474)",
        "requirements": {
            "trace_no_live_human": row("Selected trace contains no live-human method, target, or forced-submission instruction.", "Starter/Continuation Prompt; trace boundary", "evidence_supported_separate_reproduction", "later 120-minute reproduction and bounded formal prefix; not the lost original run", ["task1/evidence/canonical/rollout-solution-prefix.jsonl", "task1/evidence/rollouts/rollout-2026-08-05T17-20-55-019fd139-d180-7171-ac0b-c037e11866eb.jsonl", "task1/COMPLIANCE.md"], "The complete original run record was unavailable after a school-server restart."),
            "final_trace_alignment": row("Official final must be causally bound to the selected autonomous trace for a strict trace claim.", "Kaggle account extraction and trace provenance", "known_deviation", "official account final versus selected reproduction", ["task1/remote/FINAL_ACCOUNT_RESULTS.json", "task1/SUMMARY.json"], "The official final refs are not bound to the lost original or to the later post-deadline reproduction."),
            "exact_prompt_text": row("Use the exact organizer Starter/Continuation Prompt text.", "Starter Prompt and Continuation Prompt pages", "known_deviation_with_exact_supplement", "canonical later reproduction; supplemental formal prefix separately", ["PROMPT_CONFORMANCE_AUDIT.json", "FORMAL_PREFIX_AUDIT.json", "task1/official/OFFICIAL_PAGES_FULL.json"], "The canonical later reproduction has a custom starter appendix. The bounded formal prefix is exact-prompt evidence but has no scored pre-boundary submission."),
            "notebook_only": row("Every valid submission is generated by a Kaggle Notebook; no direct prediction-file upload.", "Kaggle CLI Submission page", "evidence_supported_candidate_not_exact", "external extraction kernel-linked candidate; exact scored version not byte-confirmed", ["task1/remote/OFFICIAL_FINAL_EXTRACTION_PROVENANCE.json", "task1/COMPLIANCE.md", "KAGGLE_EXTRACTION_SUMMARY.json"], "The archive candidate has Kaggle script-kernel metadata, source, output, and linked submission records. Its empty matched_version_confidence means this supports the candidate's notebook flow, not an exact byte-level claim for either official ref."),
            "version_budget": row("Maximum 20 notebook versions; failed/time-out pushes count.", "Kaggle CLI Submission page", "jury_interpretation_risk", "extracted account history", ["task1/SUMMARY.json", "KAGGLE_EXTRACTION_SUMMARY.json"], "38 versions were captured versus the published 20; the package cannot determine whether post-deadline activity is included by the Jury."),
            "runtime_cap": row("Each Kernel run must be capped at 600 seconds.", "Kaggle CLI Submission page", "evidence_supported_candidate_not_exact", "external extraction kernel-linked candidate; exact scored version not byte-confirmed", ["task1/remote/OFFICIAL_FINAL_EXTRACTION_PROVENANCE.json", "task1/COMPLIANCE.md", "KAGGLE_EXTRACTION_SUMMARY.json"], "The candidate metadata records 423.866203825 seconds, below 600 seconds. Because the extraction did not confirm the matched version, this is candidate runtime evidence rather than exact official-ref proof."),
            "internet_resources": row("Internet disabled; only competition data and permitted offline resources.", "Kaggle CLI Submission and competition rules", "evidence_supported_candidate_not_exact", "external extraction kernel-linked candidate plus separately scoped reproduction", ["task1/remote/OFFICIAL_FINAL_EXTRACTION_PROVENANCE.json", "task1/COMPLIANCE.md", "task1/submission/agent-executed-55267607/final/kernel-metadata.json"], "The candidate metadata records enable_internet=false, the competition bundle, and the official wheel dataset with no model or Kernel data sources. Method-background web research remains separately disclosed."),
            "hardware": row("CPU or one permitted GPU, using only cuda:0 when applicable.", "Kaggle CLI Submission and competition rules", "evidence_supported_candidate_not_exact", "external extraction kernel-linked candidate; exact scored version not byte-confirmed", ["task1/remote/OFFICIAL_FINAL_EXTRACTION_PROVENANCE.json", "task1/COMPLIANCE.md", "REPRODUCTION_COSTS.json"], "The candidate metadata records one NvidiaTeslaT4 and the source's cuda:0 use. The exact scored version is not byte-confirmed."),
            "output_artifacts": row("Required output schema and one row per dialogue; output generated by the notebook.", "Scoring and Kaggle CLI Submission pages", "evidence_supported_candidate_not_exact", "external extraction kernel-linked candidate; exact scored version not byte-confirmed", ["task1/remote/OFFICIAL_FINAL_EXTRACTION_PROVENANCE.json", "task1/COMPLIANCE.md", "task1/remote/FINAL_ACCOUNT_RESULTS.json"], "The candidate output is a 200-row filename,prediction CSV with a recorded SHA-256 and produced_output_file=true. This does not prove that its bytes are the exact bytes scored for either tied ref."),
            "technical_report": row("Submitted source carries the required 8–10 paragraph technical report.", "Report Generation Prompt page", "evidence_supported_candidate_not_exact", "external extraction kernel-linked source candidate; exact scored version not byte-confirmed", ["task1/remote/OFFICIAL_FINAL_EXTRACTION_PROVENANCE.json", "task1/COMPLIANCE.md", "task1/EXCLUSIONS.md"], "The candidate source contains ten numbered technical-report sections, but the extraction cannot byte-confirm that this source is the exact source used for either official final ref."),
            "official_deadline": row("Submit through Kaggle before the official deadline for ranking eligibility.", "Kaggle CLI Submission and account extraction", "evidence_supported_account_scope", "official account final selection", ["task1/remote/FINAL_ACCOUNT_RESULTS.json", "FINAL_SUBMISSION_RESULTS.md"], "The account final refs are deadline-eligible under the extracted highest-Public rule, but are not trace-aligned. The later reproduction is post-deadline."),
        },
    },
    "task2": {
        "competition": "ioai-2026-task-2-westlake-nlp-24",
        "official_final": "55261432 (Public 0.63583, Private 0.62500)",
        "requirements": {
            "trace_no_live_human": row("Selected trace contains no live-human method, target, or forced-submission instruction.", "Starter/Continuation Prompt; trace boundary", "evidence_supported_separate_reproduction", "later 120-minute reproduction and bounded formal prefix; not the lost original run", ["task2/evidence/reproduction-120m/rollout.jsonl", "task2/evidence/rollouts/rollout-2026-08-05T13-30-31-019fd066-e338-71a0-9d8e-6e1d154c5a79.jsonl", "task2/COMPLIANCE.md"], "The complete original run record was unavailable after a school-server restart."),
            "final_trace_alignment": row("Official final must be causally bound to the selected autonomous trace for a strict trace claim.", "Kaggle account extraction and trace provenance", "known_deviation", "official account final versus formal prefix and later reproduction", ["task2/remote/FINAL_ACCOUNT_RESULTS.json", "task2/SUMMARY.json"], "The official ExtraTrees final is downstream of the formal supervision boundary; the later reproduction is a different post-deadline submission."),
            "exact_prompt_text": row("Use the exact organizer Starter/Continuation Prompt text.", "Starter Prompt and Continuation Prompt pages", "known_deviation_with_exact_supplement", "canonical later reproduction; supplemental formal prefix separately", ["PROMPT_CONFORMANCE_AUDIT.json", "FORMAL_PREFIX_AUDIT.json", "task2/official/OFFICIAL_PAGES_FULL.json"], "The canonical later reproduction has a custom starter appendix. The bounded formal prefix is exact-prompt evidence and contains eligible v2 evidence."),
            "notebook_only": row("Every valid submission is generated by a Kaggle Notebook; no direct prediction-file upload.", "Kaggle CLI Submission page", "evidence_supported_candidate_not_exact", "external extraction kernel-linked candidate plus formal eligible v2 chain; exact scored version not byte-confirmed", ["task2/remote/OFFICIAL_FINAL_EXTRACTION_PROVENANCE.json", "task2/COMPLIANCE.md", "task2/notebooks/rotation-cnn-v2/kernel-metadata.json"], "The archive candidate has Kaggle script-kernel metadata, source, output, and linked submission records. Its empty matched_version_confidence means it cannot be called an exact official-final artifact chain; the tracked current-tree snapshot is a different v3 result."),
            "version_budget": row("Maximum 20 notebook versions; failed/time-out pushes count.", "Kaggle CLI Submission page", "evidence_supported", "extracted account history", ["task2/SUMMARY.json", "KAGGLE_EXTRACTION_SUMMARY.json"], "18 captured versions are within the published 20-version limit."),
            "runtime_cap": row("Each Kernel run must be capped at 300 seconds.", "Kaggle CLI Submission page", "evidence_supported_candidate_not_exact", "external extraction kernel-linked candidate plus eligible v2 run; exact scored version not byte-confirmed", ["task2/remote/OFFICIAL_FINAL_EXTRACTION_PROVENANCE.json", "task2/remote/rotation-cnn-v2/ioai-task2-westlake-rotation-cnn-v2.log", "task2/COMPLIANCE.md"], "The candidate metadata records 118.58038651 seconds and the candidate log is retained in the external archive; eligible v2 records 204.02 seconds. The candidate's exact scored-version relation remains unconfirmed."),
            "internet_resources": row("Internet disabled; no pretrained model or extra data beyond permitted wheel dataset.", "Kaggle CLI Submission and competition rules", "evidence_supported_candidate_not_exact", "external extraction kernel-linked candidate plus formal eligible v2 notebook metadata", ["task2/remote/OFFICIAL_FINAL_EXTRACTION_PROVENANCE.json", "task2/notebooks/rotation-cnn-v2/kernel-metadata.json", "task2/COMPLIANCE.md"], "The candidate metadata records enable_internet=false, the competition bundle and official wheel dataset, and no model or Kernel data sources. Method-background research is separately disclosed."),
            "hardware": row("CPU or one permitted GPU, using only cuda:0 when applicable.", "Kaggle CLI Submission and competition rules", "evidence_supported_candidate_not_exact", "external extraction kernel-linked candidate plus eligible v2 notebook metadata", ["task2/remote/OFFICIAL_FINAL_EXTRACTION_PROVENANCE.json", "task2/notebooks/rotation-cnn-v2/kernel-metadata.json", "task2/COMPLIANCE.md"], "The candidate metadata records one NvidiaTeslaT4, cuda:0-only source patterns, and no multi-GPU suspicion. Exact official-ref version binding remains unconfirmed."),
            "output_artifacts": row("Required id,prediction schema with one valid integer prediction per test id.", "Scoring and Kaggle CLI Submission pages", "evidence_supported_candidate_not_exact", "external extraction kernel-linked candidate plus eligible v2 output chain", ["task2/remote/OFFICIAL_FINAL_EXTRACTION_PROVENANCE.json", "task2/remote/rotation-cnn-v2/submission.csv", "task2/COMPLIANCE.md"], "The candidate output is a 7,200-row id,prediction CSV with a recorded SHA-256 and produced_output_file=true; the exact bytes scored for ref 55261432 are not byte-confirmed."),
            "technical_report": row("Submitted source carries the required technical report.", "Report Generation Prompt page", "evidence_supported_candidate_not_exact", "external extraction kernel-linked source candidate plus eligible v2 source", ["task2/remote/OFFICIAL_FINAL_EXTRACTION_PROVENANCE.json", "task2/notebooks/rotation-cnn-v2/ioai-task2-westlake-rotation-cnn-v2.py", "task2/COMPLIANCE.md"], "The candidate source contains a technical-report header and method/runtime documentation; the extraction cannot byte-confirm that source as the exact source used for ref 55261432. Historical report gaps remain disclosed."),
            "official_deadline": row("Submit through Kaggle before the official deadline for ranking eligibility.", "Kaggle CLI Submission and account extraction", "evidence_supported_account_scope", "official account final selection", ["task2/remote/FINAL_ACCOUNT_RESULTS.json", "FINAL_SUBMISSION_RESULTS.md"], "The official final is deadline-eligible under the extracted highest-Public rule, but not trace-aligned."),
        },
    },
    "task3": {
        "competition": "ioai-2026-task-3-westlake-nlp-48",
        "official_final": "55289569 / 55289823 (Public 58.51666, Private 51.61666)",
        "requirements": {
            "trace_no_live_human": row("Selected trace contains no live-human method, target, or forced-submission instruction.", "Starter/Continuation Prompt; trace boundary", "evidence_supported", "eight pre-boundary autonomous traces", ["AUTONOMOUS_TRACE_INDEX.json", "task3/AUTONOMY_BOUNDARY.md", "task3/evidence/rollouts/"], "Observable prompts, outputs, worker assignments, tool calls, and tool outputs are retained within the declared boundary."),
            "final_trace_alignment": row("Official final must be causally bound to the selected autonomous trace for a strict trace claim.", "Kaggle account extraction and trace provenance", "evidence_supported", "official final and selected autonomous v1-v8 scope", ["task3/SUMMARY.json", "task3/remote/FINAL_ACCOUNT_RESULTS.json", "task3/COMPLIANCE.md"], "The tied official Public-best refs are in the selected exact-prompt autonomous scope."),
            "exact_prompt_text": row("Use the exact organizer Starter/Continuation Prompt text.", "Starter Prompt and Continuation Prompt pages", "evidence_supported", "selected pre-intervention traces", ["task3/official/OFFICIAL_PAGES_FULL.json", "task3/official/STARTER_PROMPT_SUBSTITUTED.md", "task3/official/CONTINUE_PROMPT_EXACT.md", "PROMPT_CONFORMANCE_AUDIT.json"], "No continuation event appears in the selected traces; exact starter text and exact continuation page are preserved."),
            "notebook_only": row("Every valid submission is generated by a Kaggle Notebook; no direct prediction-file upload.", "Kaggle CLI Submission page", "evidence_supported", "official v1-v8 notebook submissions", ["task3/COMPLIANCE.md", "task3/official/SUBMISSION_WORKING_COPY.md", "task3/notebooks/"], "Metadata and remote outputs establish notebook-only submission flow."),
            "version_budget": row("Maximum 15 scored submissions; each competition submission consumes the limit.", "Kaggle CLI Submission page", "jury_interpretation_risk", "extracted account history versus autonomous scope", ["task3/SUMMARY.json", "task3/remote/FINAL_ACCOUNT_RESULTS.json", "RULE_COMPLIANCE_AUDIT.md"], "27 account submissions were captured (11 before and 16 after deadline) against a published limit of 15; the package does not choose how post-deadline activity is enforced."),
            "runtime_cap": row("One 600-second CPU budget covers the round.", "Kaggle CLI Submission and Evaluation pages", "evidence_supported", "v1-v8 local and remote artifact scope", ["task3/COMPLIANCE.md", "task3/evidence/LOCAL_REPRODUCTION.json", "task3/official/OVERVIEW_WORKING_COPY.md"], "Local full-public runs are far below 600 seconds and the notebook metadata is CPU-only."),
            "internet_resources": row("Internet disabled; only competition data and ordinary permitted libraries.", "Kaggle CLI Submission and competition rules", "evidence_supported", "selected submitted sources", ["task3/COMPLIANCE.md", "task3/official/OVERVIEW_WORKING_COPY.md", "task3/notebooks/"], "Submitted sources import standard library and NumPy only; development literature is recorded as non-runtime method background."),
            "hardware": row("CPU-only notebook for the submitted Task 3 package.", "Kaggle CLI Submission and metadata", "evidence_supported", "official v1-v8 notebook metadata", ["task3/official/SUBMISSION_WORKING_COPY.md", "task3/notebooks/"], "Metadata records enable_gpu=false and blank machine shape."),
            "output_artifacts": row("Exactly id,program_b64 rows for leaderboard-a/b with identical payloads and valid source envelope.", "Scoring and Kaggle CLI Submission pages", "evidence_supported", "all eight selected submitted versions", ["task3/evidence/verify_artifacts.py", "task3/evidence/LOCAL_REPRODUCTION.json", "task3/remote/"], "Source identity, contract execution, CSV shape, and hashes are mechanically checked."),
            "technical_report": row("Every submitted source carries an 8–10 paragraph report with required quantitative content.", "Report Generation Prompt page", "known_deviation", "historical v1-v8 reports", ["task3/REPORT_COMPLIANCE.md", "task3/COMPLIANCE.md"], "Historical reports have length and v8 score/distribution documentation errors; the package preserves them and discloses the errors."),
            "official_deadline": row("Submit through Kaggle before the official deadline for ranking eligibility.", "Kaggle CLI Submission and account extraction", "evidence_supported", "selected official final refs", ["task3/remote/FINAL_ACCOUNT_RESULTS.json", "FINAL_SUBMISSION_RESULTS.md"], "The official Public-best tied refs were sent before the deadline and are trace-aligned."),
        },
    },
    "task4": {
        "competition": "ioai-2026-task-4-westlake-nlp-24",
        "official_final": "55316818 (Public 98.41000, Private 98.32000)",
        "requirements": {
            "trace_no_live_human": row("Selected trace contains no live-human method, target, or forced-submission instruction.", "Starter/Continuation Prompt; trace boundary", "evidence_supported", "12 selected autonomous solver traces", ["AUTONOMOUS_TRACE_INDEX.json", "task4/evidence/SUPPLEMENTAL_ROLLOUT_PROVENANCE.json", "task4/COMPLIANCE.md"], "The trace is no-live-human within its declared boundary, but custom prompt events remain part of the solver context."),
            "final_trace_alignment": row("Official final must be causally bound to the selected autonomous trace for a strict trace claim.", "Kaggle account extraction and trace provenance", "evidence_supported", "version-4 selected trace and official final", ["task4/SUMMARY.json", "task4/remote/FINAL_ACCOUNT_RESULTS.json", "task4/remote/V4_OUTPUT_PROVENANCE.json"], "Version 4 source, output hash, runtime, and submission ref are bound."),
            "exact_prompt_text": row("Use the exact organizer Starter/Continuation Prompt text.", "Starter Prompt and Continuation Prompt pages", "known_deviation", "selected Task 4 trace", ["task4/official/OFFICIAL_PAGES_FULL.json", "task4/official/STARTER_PROMPT_EXACT.md", "task4/official/CONTINUE_PROMPT_EXACT.md", "task4/RULE_DIFFERENCE_AUDIT.json"], "The historical trace contains a formatting-modified starter and substantive generic continuation events; exact official bodies are provided separately for comparison."),
            "notebook_only": row("Every valid submission is generated by a Kaggle Notebook; no direct prediction-file upload.", "Kaggle CLI Submission page", "evidence_supported", "official version 4", ["task4/COMPLIANCE.md", "task4/notebooks/kernel-metadata.json", "task4/remote/V4_OUTPUT_PROVENANCE.json"], "Remote source, metadata, log, and output provenance establish the notebook flow."),
            "version_budget": row("Maximum 20 notebook versions; failed/time-out pushes count.", "Kaggle CLI Submission page", "evidence_supported", "extracted account history", ["task4/SUMMARY.json", "KAGGLE_EXTRACTION_SUMMARY.json"], "Three account submissions/versions were captured, all before the official deadline."),
            "runtime_cap": row("Each Kernel run must be capped at 600 seconds.", "Kaggle CLI Submission page", "evidence_supported", "official version 4", ["task4/COMPLIANCE.md", "task4/remote/V4_OUTPUT_PROVENANCE.json", "task4/remote/V4_KERNEL.log"], "The selected remote runtime is about 316 seconds."),
            "internet_resources": row("Internet disabled; only competition data, supplied classifiers, and permitted wheels.", "Kaggle CLI Submission and competition rules", "evidence_supported_with_method_disclosure", "official version 4 notebook", ["task4/COMPLIANCE.md", "task4/notebooks/kernel-metadata.json", "task4/RULE_DIFFERENCE_AUDIT.json"], "Two post-v3 arXiv searches are retained as provenance; no evidence shows their results entered v4 and they are not treated as a runtime-resource violation."),
            "hardware": row("CPU or one T4; use only cuda:0 on GPU.", "Kaggle CLI Submission and competition rules", "jury_interpretation_risk", "submitted notebook versus local development", ["task4/COMPLIANCE.md", "task4/notebooks/kernel-metadata.json", "task4/RULE_DIFFERENCE_AUDIT.json"], "The submitted notebook used one T4/cuda:0. Local H100 development records remain disclosed; the Jury decides the scope implication."),
            "output_artifacts": row("Exactly 200 id,delta_a,delta_b rows with valid encoded tensors.", "Scoring and Kaggle CLI Submission pages", "evidence_supported", "official version 4 output provenance", ["task4/COMPLIANCE.md", "task4/remote/V4_OUTPUT_PROVENANCE.json", "task4/remote/V4_KERNEL.log"], "Schema, row count, tensor count, output hash, and retrieval path are recorded; the large CSV is not duplicated."),
            "technical_report": row("Submitted source carries the required 8–10 paragraph technical report.", "Report Generation Prompt page", "evidence_supported_with_later_score_disclosure", "historical version-4 source", ["task4/COMPLIANCE.md", "task4/notebooks/REMOTE_CURRENT_V4.py"], "The source contains ten report paragraphs; later score/runtime facts are disclosed outside the immutable report."),
            "official_deadline": row("Submit through Kaggle before the official deadline for ranking eligibility.", "Kaggle CLI Submission and account extraction", "evidence_supported", "official version 4", ["task4/remote/FINAL_ACCOUNT_RESULTS.json", "task4/COMPLIANCE.md"], "Submission 55316818 was sent before the 06:15 UTC deadline."),
        },
    },
    "task5": {
        "competition": "ioai-2026-task-5-westlake-nlp-24",
        "official_final": "55320296 (Public 95.39000, Private 96.06000)",
        "requirements": {
            "trace_no_live_human": row("Selected trace contains no live-human method, target, or forced-submission instruction.", "Starter/Continuation Prompt; trace boundary", "evidence_supported", "selected pre-deadline autonomous trace", ["AUTONOMOUS_TRACE_INDEX.json", "task5/COMPLIANCE.md", "task5/evidence/rollouts/"], "The main solver received the exact Starter Prompt and no continuation; controller status messages were not solver inputs."),
            "final_trace_alignment": row("Official final must be causally bound to the selected autonomous trace for a strict trace claim.", "Kaggle account extraction and trace provenance", "evidence_supported", "official version 6 and selected trace", ["task5/SUMMARY.json", "task5/remote/FINAL_ACCOUNT_RESULTS.json", "task5/V6_SOURCE_PROVENANCE.json"], "The source is trace-preserved and bound to version 6; Kaggle's historical source endpoint now returns 403, which is disclosed."),
            "exact_prompt_text": row("Use the exact organizer Starter/Continuation Prompt text.", "Starter Prompt and Continuation Prompt pages", "evidence_supported", "selected Task 5 trace", ["task5/official/OFFICIAL_PAGES_FULL.json", "task5/official/STARTER_PROMPT_EXACT.md", "task5/official/CONTINUE_PROMPT_EXACT.md", "PROMPT_CONFORMANCE_AUDIT.json"], "Selected traces contain exact Starter Prompt text and no continuation event."),
            "notebook_only": row("Every valid submission is generated by a Kaggle Notebook; no direct prediction-file upload.", "Kaggle CLI Submission page", "evidence_supported", "official version 6", ["task5/COMPLIANCE.md", "task5/notebooks/kernel-metadata.json", "task5/remote/v6/"], "Notebook metadata, exact output, log, and submission record are retained."),
            "version_budget": row("Maximum 15 notebook versions; failed/time-out pushes count.", "Kaggle CLI Submission page", "evidence_supported", "extracted account history", ["task5/SUMMARY.json", "KAGGLE_EXTRACTION_SUMMARY.json"], "Seven captured versions are within the published 15-version limit."),
            "runtime_cap": row("Each Kernel run must be capped at 600 seconds.", "Kaggle CLI Submission page", "evidence_supported", "official version 6", ["task5/COMPLIANCE.md", "task5/remote/v6/ioai-2026-ghost-of-the-machine-solution.log"], "The v6 remote log records about 289.3 seconds."),
            "internet_resources": row("Internet disabled; only the permitted local bge-base-en-v1.5 and competition data.", "Kaggle CLI Submission and competition rules", "evidence_supported_with_method_disclosure", "official version 6 notebook", ["task5/COMPLIANCE.md", "task5/notebooks/kernel-metadata.json", "task5/official/OVERVIEW.md"], "External literature search is retained as method-background provenance; no external runtime data, weights, or API entered the submitted notebook."),
            "hardware": row("CPU or one T4; use only cuda:0 on GPU.", "Kaggle CLI Submission and competition rules", "evidence_supported", "official version 6 notebook", ["task5/COMPLIANCE.md", "task5/notebooks/kernel-metadata.json", "task5/remote/v6/ioai-2026-ghost-of-the-machine-solution.log"], "The submitted notebook used one Tesla T4 on cuda:0; local H100 accounting is a separate incomplete cost scope."),
            "output_artifacts": row("Exactly 760 id,boundary_char_index rows with integer in-range predictions.", "Scoring and Kaggle CLI Submission pages", "evidence_supported", "official version 6", ["task5/COMPLIANCE.md", "task5/remote/v6/submission.csv", "task5/remote/v6/ioai-2026-ghost-of-the-machine-solution.log"], "The exact archived output and log are retained and hash-bound."),
            "technical_report": row("Submitted source carries the required 8–10 paragraph technical report.", "Report Generation Prompt page", "evidence_supported_with_later_score_disclosure", "preserved version-6 source", ["task5/COMPLIANCE.md", "task5/notebooks/BEST_V6_SOURCE.py"], "The source contains ten report paragraphs; later platform facts are documented outside it."),
            "official_deadline": row("Submit through Kaggle before the official deadline for ranking eligibility.", "Kaggle CLI Submission and account extraction", "evidence_supported", "official version 6", ["task5/remote/FINAL_ACCOUNT_RESULTS.json", "task5/COMPLIANCE.md"], "Version 6 was submitted before the deadline; version 7 was late and is not substituted."),
        },
    },
    "task6": {
        "competition": "ioai-2026-task-6-westlake-nlp-60",
        "official_final": "55357080 (Public 75.01540, Private 73.36234)",
        "requirements": {
            "trace_no_live_human": row("Selected trace contains no live-human method, target, or forced-submission instruction.", "Starter/Continuation Prompt; trace boundary", "evidence_supported", "selected pre-intervention autonomous trace", ["AUTONOMOUS_TRACE_INDEX.json", "task6/COMPLIANCE.md", "task6/evidence/autonomous-only/"], "The selected main and worker traces contain exact Starter Prompt text and no continuation event."),
            "final_trace_alignment": row("Official final must be causally bound to the selected autonomous trace for a strict trace claim.", "Kaggle account extraction and trace provenance", "evidence_supported", "official version 3 and selected trace", ["task6/SUMMARY.json", "task6/remote/FINAL_ACCOUNT_RESULTS.json", "task6/ARTIFACT_PROVENANCE.json"], "The exact v3 source, weights, CSV, decoded code, and submission ref are aligned."),
            "exact_prompt_text": row("Use the exact organizer Starter/Continuation Prompt text.", "Starter Prompt and Continuation Prompt pages", "evidence_supported", "selected Task 6 trace", ["task6/official/OFFICIAL_PAGES_FULL.json", "task6/official/STARTER_PROMPT_EXACT.md", "task6/official/CONTINUE_PROMPT_EXACT.md", "PROMPT_CONFORMANCE_AUDIT.json"], "Selected traces contain exact Starter Prompt text and no continuation event."),
            "notebook_only": row("Every valid submission is generated by a Kaggle Notebook; no direct prediction-file upload.", "Kaggle CLI Submission page", "evidence_supported", "official version 3", ["task6/COMPLIANCE.md", "task6/notebooks/v3/kernel-metadata.json", "task6/remote/v3/submission.csv"], "Notebook metadata and exact submission envelope are retained."),
            "version_budget": row("Maximum 20 notebook versions; failed/time-out pushes count.", "Kaggle CLI Submission page", "evidence_supported", "extracted account history", ["task6/SUMMARY.json", "KAGGLE_EXTRACTION_SUMMARY.json"], "Eight captured versions are within the published 20-version limit."),
            "runtime_cap": row("Each Kernel run must be capped at 600 seconds.", "Kaggle CLI Submission page", "evidence_supported", "official v3 and autonomous remote versions", ["task6/COMPLIANCE.md", "task6/remote/v3/", "task6/official/SUBMISSION.md"], "The selected v3 run is in the required timeout scope; exact logs and runtime provenance are retained."),
            "internet_resources": row("Internet disabled; only permitted packages, public config/API, and competition resources.", "Kaggle CLI Submission and protected-runtime rules", "evidence_supported_with_technical_disclosure", "official v3 notebook and selected trace", ["task6/COMPLIANCE.md", "task6/notebooks/v3/kernel-metadata.json", "task6/RULE_DIFFERENCE_AUDIT.json"], "The protected evaluator was not redistributed or reverse engineered. Measured evaluator-batch dependence is disclosed as a technical property, not classified here as a violation."),
            "hardware": row("CPU or one T4; use only cuda:0 on GPU.", "Kaggle CLI Submission and competition rules", "evidence_supported", "official v3 notebook", ["task6/COMPLIANCE.md", "task6/notebooks/v3/kernel-metadata.json"], "The submitted notebook used the permitted one-T4/cuda:0 scope; local H100 total remains an incomplete accounting issue."),
            "output_artifacts": row("Exactly id,model_b64,code_b64 with identical leaderboard-a/b payloads and valid model envelope.", "Scoring and Kaggle CLI Submission pages", "evidence_supported", "official v3 exact artifact chain", ["task6/ARTIFACT_PROVENANCE.json", "task6/remote/v3/submission.csv", "task6/remote/v3/custom_model.py", "task6/tools/verify_v3_artifacts.py"], "CSV identity, decoded source, safetensors state, parameter count, and hashes are mechanically checked."),
            "technical_report": row("Submitted source carries the required 8–10 paragraph technical report.", "Report Generation Prompt page", "known_deviation", "historical v3 report", ["task6/COMPLIANCE.md", "task6/RULE_DIFFERENCE_AUDIT.json"], "The immutable report contains dropout/range factual errors; the source is preserved and the correction is disclosed."),
            "official_deadline": row("Submit through Kaggle before the official deadline for ranking eligibility.", "Kaggle CLI Submission and account extraction", "evidence_supported", "official version 3", ["task6/remote/FINAL_ACCOUNT_RESULTS.json", "task6/COMPLIANCE.md"], "The selected v3 result was submitted before the official deadline; later numerical maxima are not substituted."),
        },
    },
}


def build() -> dict[str, Any]:
    tasks: dict[str, Any] = {}
    for task, data in TASKS.items():
        tasks[task] = {
            "competition": data["competition"],
            "official_final": data["official_final"],
            "requirements": data["requirements"],
        }
    return {
        "schema": "ioai.requirement-evidence-matrix.v1",
        "generated_by": "tools/build_requirement_evidence_matrix.py",
        "purpose": "One-row-per-requirement navigation; not an organizer compliance certificate.",
        "status_definitions": {
            "evidence_supported": "The cited package evidence supports the requirement in the stated scope.",
            "evidence_supported_separate_reproduction": "Supported for a separate reproduction/prefix, not the official final claim.",
            "evidence_supported_artifact_scope": "Supported by an artifact chain whose causal/autonomy scope is stated separately.",
            "evidence_supported_candidate_not_exact": "The external extraction provides a strongly identified kernel-linked candidate supporting the stated property, but its exact version or scored bytes are not independently byte-confirmed.",
            "evidence_supported_account_scope": "Supported for the extracted account deadline/selection scope, not necessarily trace causality.",
            "evidence_partially_available": "Some positive evidence exists, but the repository cannot prove the universal negative or historical fact.",
            "known_deviation": "Evidence directly conflicts with the stated requirement or strict claim scope.",
            "known_deviation_with_exact_supplement": "Canonical claim is non-exact, while a separate bounded exact-prompt supplement exists.",
            "jury_interpretation_risk": "Facts are established but organizer/Jury interpretation remains necessary.",
            "evidence_unavailable_for_official_final": "The historical official-final fact/artifact cannot be reconstructed from retained records.",
            "evidence_supported_with_disclosure": "Supported, with a separate factual/report/provenance limitation that is not silently repaired.",
            "evidence_supported_with_later_score_disclosure": "Supported; later platform observations remain outside the immutable submitted report.",
            "evidence_supported_with_method_disclosure": "Supported for runtime resources; development method-background research is separately disclosed.",
            "evidence_supported_with_technical_disclosure": "Supported for the operational rule; a measured technical behavior is separately disclosed.",
        },
        "common_requirements": COMMON,
        "tasks": tasks,
        "overall": {
            "strict_all_six_claim": False,
            "main_unresolved_items": [
                "Task 1/2 lost-original provenance and final-result trace alignment",
                "Task 1/2 later reproduction custom starter and post-deadline scope",
                "Task 1/3 account-history budget interpretation",
                "Task 4 non-exact continuation and local-H100 interpretation",
                "Task 5 historical v6 source re-download 403",
                "Task 3/6 historical report factual/format limitations",
                "exhaustive local H100 runtime and USD cost reconstruction",
            ],
        },
    }


def markdown(data: dict[str, Any]) -> str:
    lines = [
        "# Requirement-to-evidence matrix",
        "",
        "This is a navigation and scope-control document for organizer/Jury review.",
        "It is not a self-issued compliance certificate. Every status is tied to the",
        "scope and evidence paths in the machine-readable JSON beside this file.",
        "",
        "| Task | Requirement | Status | Evidence scope | Primary evidence |",
        "|---|---|---|---|---|",
    ]
    for rid, item in data["common_requirements"].items():
        evidence = "; ".join(f"`{p}`" for p in item["evidence"][:3])
        lines.append(f"| all tasks | {rid}: {item['requirement']} | **{item['status']}** | {item['scope']} | {evidence} |")
    for task, info in data["tasks"].items():
        for rid, item in info["requirements"].items():
            evidence = "; ".join(f"`{p}`" for p in item["evidence"][:3])
            lines.append(f"| {task} | {rid}: {item['requirement']} | **{item['status']}** | {item['scope']} | {evidence} |")
    lines += [
        "",
        "## Reading the statuses",
        "",
        "- `evidence_supported*` means only the stated evidence scope is supported.",
        "- `known_deviation` records a conflict; it is not converted into a green check by the package.",
        "- `jury_interpretation_risk` and `evidence_partially_available` require organizer/Jury judgment.",
        "- Task 1/2 reproduction and formal-prefix evidence must not be substituted for the lost original official-final run.",
        "",
        "The complete notes, all evidence paths, and official-page labels are in",
        "[`REQUIREMENT_EVIDENCE_MATRIX.json`](REQUIREMENT_EVIDENCE_MATRIX.json).",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    data = build()
    (ROOT / "REQUIREMENT_EVIDENCE_MATRIX.json").write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (ROOT / "REQUIREMENT_EVIDENCE_MATRIX.md").write_text(markdown(data), encoding="utf-8")
    print(json.dumps({task: len(v["requirements"]) for task, v in data["tasks"].items()}, sort_keys=True))


if __name__ == "__main__":
    main()
